
package co.edu.eam.ingesoft.pa2.serviciosAcademicos;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviciosAcademicos", targetNamespace = "http://www.eam.edu.co")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosAcademicos {


    /**
     * 
     * @param ced
     * @param cod
     * @return
     *     returns co.edu.eam.ingesoft.pa2.serviciosAcademicos.Estudiante
     */
    @WebMethod
    @WebResult(name = "estudiante", targetNamespace = "")
    @RequestWrapper(localName = "consultaEstudiante", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.ConsultaEstudiante")
    @ResponseWrapper(localName = "consultaEstudianteResponse", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.ConsultaEstudianteResponse")
    public Estudiante consultaEstudiante(
        @WebParam(name = "cod", targetNamespace = "")
        String cod,
        @WebParam(name = "ced", targetNamespace = "")
        String ced);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.InitResponse")
    public void init();

    /**
     * 
     * @param ced
     * @param cod
     * @return
     *     returns java.util.List<co.edu.eam.ingesoft.pa2.serviciosAcademicos.Curso>
     */
    @WebMethod
    @WebResult(name = "listaCursos", targetNamespace = "")
    @RequestWrapper(localName = "consultarCursosEstudiante", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.ConsultarCursosEstudiante")
    @ResponseWrapper(localName = "consultarCursosEstudianteResponse", targetNamespace = "http://www.eam.edu.co", className = "co.edu.eam.ingesoft.pa2.serviciosAcademicos.ConsultarCursosEstudianteResponse")
    public List<Curso> consultarCursosEstudiante(
        @WebParam(name = "cod", targetNamespace = "")
        String cod,
        @WebParam(name = "ced", targetNamespace = "")
        String ced);

}
